apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-session
  namespace: flink
spec:
  image: flink:1.20
  flinkVersion: v1_20
  serviceAccount: flink

  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    parallelism.default: "2"

  jobManager:
    resource:
      memory: "1024m"
      cpu: 1

  taskManager:
    resource:
      memory: "2048m"
      cpu: 1

  mode: standalone
